# Generated by Django 6.0.4 on 2026-08-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='area',
        ),
        migrations.AddField(
            model_name='teacher',
            name='area',
            field=models.ManyToManyField(blank=True, to='Content.subject'),
        ),
    ]
