# Generated by Django 6.0.4 on 2026-08-12 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_remove_teacher_area_teacher_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='area',
            new_name='areas',
        ),
    ]
