# Generated by Django 6.0.4 on 2026-08-12 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_rename_area_teacher_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('subjects', models.ManyToManyField(blank=True, to='Content.subject')),
            ],
        ),
    ]
