# Generated by Django 6.0.4 on 2026-08-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='No department provided.', max_length=40),
        ),
    ]
