# Generated by Django 6.0.4 on 2026-08-14 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0006_teacher_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='areas',
            new_name='subjects',
        ),
    ]
