# Generated by Django 6.0.4 on 2026-08-14 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0007_rename_areas_teacher_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(max_length=40),
        ),
    ]
