# Generated by Django 6.0.4 on 2026-08-14 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0008_alter_teacher_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='subjects',
            new_name='areas',
        ),
    ]
