# Generated by Django 6.0.4 on 2026-08-14 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0009_rename_subjects_teacher_areas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
