# Generated by Django 6.0.4 on 2026-08-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0010_remove_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='No department selected.', max_length=40),
        ),
    ]
