# Generated by Django 6.0.4 on 2026-08-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0011_teacher_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(max_length=40),
        ),
    ]
