# Generated by Django 6.0.4 on 2026-08-16 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0013_rename_areas_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_level',
            field=models.IntegerField(default=10),
        ),
    ]
