# Generated by Django 6.0.4 on 2026-08-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0014_student_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.IntegerField(),
        ),
    ]
