# Generated by Django 6.0.4 on 2026-08-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0017_unit_alter_student_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
