# Generated by Django 6.0.4 on 2026-08-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0018_alter_unit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
