# Generated by Django 6.0.4 on 2026-08-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0020_alter_unit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
