# Generated by Django 6.0.4 on 2026-08-20 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0021_alter_unit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='course_code',
            field=models.CharField(default='A', max_length=10),
        ),
        migrations.AddField(
            model_name='unit',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Content.teacher'),
        ),
    ]
