# Generated by Django 6.0.4 on 2026-08-20 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0022_unit_course_code_unit_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.teacher'),
        ),
    ]
