# Generated by Django 6.0.4 on 2026-08-20 01:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0023_alter_unit_course_code_alter_unit_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOutline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_period', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=10)),
                ('year_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Content.subject')),
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Content.unit')),
            ],
        ),
    ]
