# Generated by Django 6.0.4 on 2026-08-20 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0024_unitoutline'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitoutline',
            name='content_descriptions',
            field=models.TextField(default='A'),
        ),
        migrations.AddField(
            model_name='unitoutline',
            name='unit_goals',
            field=models.TextField(default='A'),
        ),
    ]
