# Generated by Django 6.0.4 on 2026-08-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0025_unitoutline_content_descriptions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitoutline',
            old_name='course_code',
            new_name='accreditation',
        ),
    ]
