# Generated by Django 6.0.4 on 2026-08-21 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0026_rename_course_code_unitoutline_accreditation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitoutline',
            name='content_descriptions',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='unitoutline',
            name='unit_goals',
            field=models.TextField(),
        ),
    ]
